- Dockerfile
- Jenkinsfile
Initial `Dockerfile` and `Image` build stage.
> Docker image

- Jenkinsfile
Deploy to discovery environment when `dd-develop` is pushed to.
Test the logic in a Vagrant build environment, make sure the correct deployment groups are selected for the corresponding branch.
Anyone but myself.
> Deploy dd-develop to discovery environment

- scripts/codedeploy/application-start.sh
Add `DATADISCOVEY_URL` configuration item.
Check the correct environment variable is being set.
Anyone but myself.
> Configuration for data discovery URL

- scripts/codedeploy/application-start.sh
Pass through `SPLASH_PAGE` env var to docker
Check env var is passed through
> add config for splash page

- Makefile
- ci/build-bundle.yml
- ci/build.yml
- ci/deployment-bundle.yml
- ci/replace-vars.yml
- ci/revision.yml
- ci/scripts/build-bundle.sh
- ci/scripts/build.sh
- ci/scripts/deployment-bundle.sh
- ci/scripts/replace-vars.sh
- ci/scripts/revision.sh
- ci/scripts/unit.sh
- ci/scripts/unpack.sh
- ci/unit.yml
- ci/unpack.yml
See https://github.com/ONSdigital/dp-dd-file-uploader/pull/14
> feature-concourse

- scripts/codedeploy/application-start.sh
Updated environment config to fix welsh site redirect not working in discovery & discovery develop envs
> Updated Environment config to fix cy redirect

- main.go
- Added mappings from the api response model to the frontend model
- Removed any reference to CMD in the code
- Updated URLs from `/jobs/{jobID}` to `/filters/{filterID}`
- Checkout feature/api-to-frontend-model on dp-frontend-filter-dataset-controller, dp-frontend-dataset-controller, dp-frontend-renderer, dp-frontend-router
- Run the services and visit http://localhost:20000/filters/123456/dimensions
- Verify the page continues to work as expected
Anyone
> Update job_id to become filter_id

- assets/templates.go
- main.go
Remove dodgy timeouts
🐠 
@Crispioso @jondewijones
> remove dodgy timeouts

- main.go
> fix sameorigin bug

- vendor/github.com/ONSdigital/go-ns/handlers/reverseProxy/reverseProxy.go
- vendor/vendor.json
> Add vendored dep

- middleware/allRoutes/handler.go
To test this, you will need the following services running:
- dp-frontend-router
- dp-frontend-dataset-controller
- dp-frontend-filter-dataset-controller
- dp-frontend-router
- sixteens
- dp-frontend-renderer
- zebedee
- babbage
- dp-dataset-api
- dp-filter-api
- dp-import-api
- dp-recipe-api
- dp-code-list-api
- dp-hierarchy-api
- dp-dimension-extractor
- dp-dimension-importer
- dp-observation-exporter
- dp-observation-importer
- dp-import-tracker
- dp-dataset-exporter
You will then need to export the CPI dataset locally. If you haven't done this already and don't know how to, then I will help with this!
Once you have imported the dataset, then in mongodb, you will have a datasets collection. Use the _id field in mongodb to create a dataset.json file which looks like:
```
{ …
```
> Update frontend journey to use dataset api

- main.go
Add feedback form to CMD journey for feedback
Run:
sixteens,
dp-frontend-router,
dp-frontend-dataset-controller,
renderer (`feature/feedback`)
on `feature/feedback-form`
Verify that the feedback form is visible on all CMD pages, and that you can send feedback which appears in the feedback channel on slack. Please note you will need to create a slack token here https://api.slack.com/custom-integrations/legacy-tokens, and set it as the environment variable:
`export SLACK_TOKEN=<SLACK_TOKEN>`
You should also be able to access the feedback form via the beta banner at the top. Note you should get an error if you do not provide a description field
Team A
> Route feedback form to frontend controller

- main.go
Update filter job creation to match new filter api spec
Create a filter job through the web UI
Add dimension options to the job
Submit the job and verify the url changes to /filter-ouputs/{id}
Verify that when you click the adjust filter options button you return to /filters/{id}/dimensions
Anyone **DO NOT MERGE UNTIL BACKEND SERVICES HAVE BEEN MERGED**
> Add routing to filter dataset controller for /filter-outputs endpoints

- middleware/allRoutes/handler.go
In our routing middleware were leaving leaving the req body open in most cases and not draining the body after we'd used it.
Quick code check and running any tests that previously caused the router to fall over.
Anyone but me.
> Fix req body closure

- middleware/serverError/handler.go
Added a refresh page link to the error handler for a 500 error.
Force a 500 error and check that the link renders and refreshes the page when clicked.
Anyone.
> Added refresh link in the handler for 500 error

- Makefile
- assets/templates.go
- config/config.go
- main.go
Remove REDIRECTS_ENABLED flag from config
Review and test
@ian-kent
> Remove REDIRECTS_ENABLED flag from config

- main.go
- middleware/allRoutes/handler.go
- middleware/serverError/handler.go
- vendor/github.com/ONSdigital/go-ns/render/render.go
- vendor/vendor.json
Merge cmd-develop into cmd-master
> Cmd develop

- assets/redirects/redirects.csv
From 
/inflationandpriceindices/qmis/consumerpriceinflationqmi
To
/economy/inflationandpriceindices/methodologies/consumerpriceinflationincludesall3indicescpihcpiandrpiqmi
Describe what you have changed and why.
Describe the steps required to test the changes.
Describe who worked on the changes, so that other people can review.
> New redirect

- middleware/serverError/handler.go
Handle a 401 response with correct error page
> Handle a 401 response with correct error page

- README.md
- scripts/codedeploy/application-start.sh
Pass through environment variables required for analytics tracking
Check application-start.sh has the right stuff in
> pass through config options for analytics

- Dockerfile
- Dockerfile.concourse
Update dockerfile to use image with root certs
Check dockerfiles look ok
> update dockerfile to add root certs

- dp-frontend-router.nomad
Allow for splitting the nomad classes.
Ensure the nomad class constraints are correct.
Anyone but me.
> Allow for splitting the nomad classes

- config/config.go
- main.go
Add config flag for analytics
*** You will need to add config flag in bleed
> Config flag for analytics

- config/config.go
- main.go
This reverts commits:
* 5e5281246f94b63dda41af930e5567e74f4072d4
* 3be9b32146b22d8cbc521605b4d1fff7ba5b7ce7
* 8a4b0b621081a027a1cb855f39f6e6c0ecdcb8e4
* f8dcca7842d5b7e3d08a26c632718cac1d36831d
* 392bc567ce91cb70981e65f32397f4718b4d3955
Ensure the above commits are reverted.
Anyone but me.
> Revert "Config flag for analytics"

- dp-frontend-router.nomad
Restrict deployment to only non-mount instances to ensure the special mount instances are kept clear for the apps that require them.
Ensure the node pattern no longer matches the mount nodes.
Anyone but me.
> Restrict deployment to non-mount instances

- config/config.go
- main.go
added a feature flag for geography
secrets https://github.com/ONSdigital/dp-ci/pull/501
feature flag disabled geography
all
> added geography feature flag

- assets/redirects/redirects.csv
/ashe 
REDIRECTS TO:
/surveys/informationforbusinesses/businesssurveys/annualsurveyofhoursandearningsashe
&
/aboutus/transparencyandgovernance/dataprotection/privacyinformationforhealthandlifeeventsdivision
REDIRECTS TO:
/aboutus/transparencyandgovernance/dataprotection/privacyinformationforourstakeholders
Check the redirects work as above.
Not Rob
> New redirects

- assets/redirects/redirects.csv
Redirect to XML file on CND (seperate PR - https://github.com/ONSdigital/cdn.ons.gov.uk-assets/pull/31) to make it look like validation file is available at the root.
Describe the steps required to test the changes.
Describe who worked on the changes, so that other people can review.
> bing validation redirect

- middleware/allRoutes/handler.go
- vendor/github.com/pkg/errors/LICENSE
- vendor/github.com/pkg/errors/README.md
- vendor/github.com/pkg/errors/appveyor.yml
- vendor/github.com/pkg/errors/errors.go
- vendor/github.com/pkg/errors/stack.go
- vendor/vendor.json
More logging to diagnose front end oom issue.
Sanity check.
Anyone.
> added additional logging

- middleware/allRoutes/handler.go
More logging for allroutes handler, force requestID's.
Will revert some of this once we know what the fix is.
Sanity check.
Anyone.
> additional logging

- dp-frontend-router.nomad
Adding restarts that are present in develop but not in cmd-dev.
Sanity check.
Anyone.
> nomad restarts

- middleware/allRoutes/handler.go
- middleware/redirects/redirects.go
More logging plus recovery to try and catch panics.
Fully intend to take most of the bumf out once we know what's going on.
Sanity check.
Anyone.
> more logging plus recovery

- middleware/serverError/handler.go
More logging, error page this time.
> added logging to error page

- middleware/allRoutes/handler.go
Manually avoid recalling serveHTTP.
> explicitly avoid further calls

- main.go
Remove the abHandler and homepage handler.
> disable homepage handler

- middleware/serverError/handler.go
Better logging in error handler.
> more logging in error handling

- main.go
Match server settings in develop/prod.
> add better server timeouts

- dp-frontend-router.nomad
Add healthcheck to nomad plan and fix typo.
Ensure nomad plan is valid.
Anyone but me.
> Add healthcheck to nomad plan

- assets/templates.go
- middleware/serverError/handler.go
Merge small changes that are in cmd-dev into dev
> Merge cmd-dev into develop

- assets/redirects/redirects.csv
Describe what you have changed and why.
Describe the steps required to test the changes.
Describe who worked on the changes, so that other people can review.
> new redirect shortcut

- assets/templates.go
Change, just to force a new deployment. This should be used to update secrets for switching on CMD feature flags.
Check nothing has actually changed that would effect functionality,
Ensure secrets have been merged in first https://github.com/ONSdigital/dp-ci/pull/711
> Trigger build to deploy secrets

- config/config.go
As per title no change other than white space
Ensure nothing has changed other than white space
> Empty change just to trigger build in CI

- config/config.go
Hotfix - Trigger rebuild (so that secrets kick in)
Checkout branch ensure nothing has changed except the removal on unneeded whitespace.
> Empty commit (whitespace removed)

- config/config.go
Trigger deploy - turn CMD off again
Check nothing has changed other than a whitespace
> Trigger deploy (turn cmd off)

- config/config.go
Build app again with new secrets
Check nothing has change other than a whitespace character
> Trigger build

- assets/templates.go
Trigger build hotfixes were created on master, this PR is simply to update develop with the commits on master
Check nothing extra that isn't on master already has been merged in with this.
> Hotfixes back into develop

- analytics/backend_sqs.go
- analytics/service.go
- go.mod
- go.sum
- handlers/analytics/handler.go
- main.go
- middleware/allRoutes/handler.go
- middleware/redirects/redirects.go
- Update to health check version v1.0.0
- Added logging severity
- Unit tests should pass
- Logging severity as expected
- /health endpoint should work as expected
Anyone.
> Upgraded to healthcheck version 1.0.0 and severity levels

- Makefile
- ci/audit.yml
- ci/scripts/audit.sh
Add audit of dependency vulnerabilities to CI build using [nancy](https://github.com/sonatype-nexus-community/nancy).
Anyone but me.
> Add vulnerability audit to CI build

- assets/redirects/redirects.csv
Add redirect for `/studycontact` to `/aboutus/whatwedo/programmesandprojects/studycontact`
Anyone but me.
> Add redirect for `/studycontact`

- assets/redirects/redirects.csv
Release for high priority redirect work (centre for equalities and inclusions)
Sense check
Anyone but me
> add centre for equalities and inclusion redirect

- config/config.go
Push the fix that should fix prod
> Release 1.15.0

- middleware/allRoutes/handler.go
Fix length check for content type byte limit
check router continues to behave as expected
anyone
> Fix content length check to avoid unnecessary deserialization

- analytics/service.go
Remove random debug line that was dumping out the search analytics to log and spamming the logs.
Anyone but me.
> Remove random debug line

- assets/redirects/redirects.csv
Add `/householdstudies` redirect
Ensure no other changes present
Anyone
> Add /householdstudies redirect

- config/config.go
- config/config_test.go
- main.go
**Describe what you have changed and why.**
- Add `/search` route
- Feature flag added to the search route
- Update config with search information
**Describe the steps required to test the changes.**
- Check if the code makes sense
- Check if the code aligns with how other routes have been added to the frontend-router
**Describe who worked on the changes, so that other people can review.**
Anyone - Justin made the changes
> add search controller route

- config/config.go
- config/config_test.go
- main.go
Added route for my new service (dp-frontend-feedback-controller) to dp-frontend-router
Make sure that all changes are correct and confirm whether anything else needs to be added
Anyone
> added route for dp-fronted-feedback-controller to dp-frontend-router

- README.md
Added empty line to force CI rebuild
Anyone
> Added empty line to force CI rebuild

- README.md
- config/config.go
- main.go
Remove FeedbackEnabled feature flag, as per this ticket - https://trello.com/c/N5RCQBej/5057-frontend-router-remove-feedbackenabled-feature-flag-05d
Confirm changes are correct
Anyone
> Remove FeedbackEnabled feature flag

- handlers/abtest/search.go
- handlers/abtest/search_test.go
- router/router.go
Add exit to search handler
Anyone
> Add exit to search handler

- config/config.go
- config/config_test.go
- main.go
- router/router.go
Add new route for census hub page
Anyone
> Add new route for census hub page

- README.md
Add missing proxy timeout config to README.
Ensure the change looks correct.
!me
> Add proxy timeout config to README

- README.md
- main.go
- middleware/allRoutes/handler.go
The proxy timeout configuration was only adjusting the timeout for the
dialer to establish the connection, not the actual wait for the upstream
service to respond. The write timeout allows for delays in the upstream
service.
Also fix a log line that was logging the users' access token 😱 
Ensure that the changes make sense.
!me
> Fix proxy timeout 

- README.md
- main.go
- middleware/allRoutes/handler.go
* Fix access token being logged out
* Fix proxy timeout configuration option
> Release 1.39.0

- handlers/abtest/search.go
A/B test cookie for search not working as expected, hence the logs,
these should later be removed
meh, just a bunch of logs - it should be fine if it compiles
Jon
> Testing ab cookie with additional logging

- config/config.go
- config/config_test.go
- main.go
- router/router.go
Remove census hub feat flags
Anyone
> Remove census hub feat flags

- router/router.go
- router/router_test.go
We are essentially replicating the behaviour of `/visualisations/` for `/interactives/` - the new path for interactives.
ASFAIK this is so third-party websites can embed charts/interactive pages within their content.
Eyeball enough I think and check tests pass.
Anyone
> Skip x-frame-options header on /interactives/

- main.go
Hotfix to make the read timeout of the http server the same as the write timeout.
Tests work etc.
Anyone but me
> Config read timeout to match write timeout

- main.go
Hotfix to increase idle timeouts on the reverse proxies
Tests pass etc.
Anyone but me
> Double idle timeout for reverse proxies to 180s

- main.go
- router/router.go
**Describe what you have changed and why.**
- Wasn't handling `/searchdata` and `/searchpublication` correctly but now this is fixed
**Describe the steps required to test the changes.**
- Check if the code changes make sense
**Describe who worked on the changes, so that other people can review.**
- Anyone
> fix search redirect in sandbox

- assets/redirects/redirects.csv
> add new redirect geography redirect to national archives

- config/config.go
Disable logging of keys on startup
Ensure the sensitive fields aren't logged on startup via the `got service configuration` event.
Anyone but me
> Disable logging of keys on startup

- config/config.go
Release branch containing…
- Disable logging of keys on startup
Ensure only the expected commits are contained in PR and tests pass.
Anyone but me
> Release 1.48.1

- assets/redirects/redirects.csv
See title
Check redirect works
Anyone
> Add redirect from /census/ to /census

- assets/redirects/redirects.csv
add new short url for business survey request
Anyone
> add new short url for business survey request

- go.mod
- go.sum
Hotfix update to api clients go
> hotfix updating api clients go

- assets/redirects/redirects.csv
Materials have gone out with this mixed case url. 
Although this goes against standards, it's been agreed we'd make an exception in this case.
👀 
Anyone
> Add redirect to veterans survey with mixed case

- assets/redirects/redirects.csv
> Merge master back into develop

- Dockerfile
- Dockerfile.concourse
- Makefile
As per title
Check container image is available.
Anyone
> Update container base to Ubuntu 20.04

- README.md
- config/config.go
- main.go
- router/router.go
- router/router_test.go
Added feature flagged routing for new dataset finder. 
Check release is constructed properly with only expected features.
Developer
> add routing for dataset finder

- Makefile
merge release changes from master into develop
review the changes
anyone
> Merge Master into develop

- config/config.go
- config/config_test.go
Enable release calendar ab testing for 100 persent inclusive. Address issue with the return to old service link.
Changes ok. Test pass.
Anyone
> Enable release calendar ab testing for 100 persent inclusive

- router/router.go
Added releases to the A/B test handler - this ensures that the link to 'return to previous version' will work. 
Check ok. 
Not me.
> Ensure old releases are available from link

- README.md
Add `OTEL_ENABLED ` in the README
Anyone from ONS
> Add otel env variable into the Readme

- README.md
- config/config.go
- config/config_test.go
- router/router.go
- router/router_test.go
Added topic filtered aggregation pages behind feature flag. 
Check code looks good, tests pass, feature flag makes sense and documented appropriately. 
Optionally run it with the latest develop branch for dp-frontend-search-controller and turn the aggregated pages on there. (will require port forwarding to sandbox to get results)
Not me.
> Add feature flagged topic aggregated pages

- main.go
Actually passed the new env var to the router.
Check looks ok - optionally, can run with search pages enabled and topic aggregation pages enabled and see requests get passed to the right handler. 
Not me.
> Correctly pass config var

- router/router.go
Route relcal through the proxy if still babbage
Switch on legacy cache and not rel cal and see that it tries to hit the proxy.
Code / tests too. 
Not me.
> Route relcal through proxy

- assets/redirects/redirects.csv
Add new short urls
(https://onswebsite.slack.com/archives/CDYNDM0HG/p1716543957697669)
Changes ok tests pass.
Anyone
> Add new short urls

- router/router.go
- router/router_test.go
allow 3 or more level topic aggregation pages
Check release is okay
Anyone
> allow 3 or more level topic aggregation pages

- dp-frontend-router.nomad
As per title.
No ONS libs have been updated.
Ensure changes are similar to whats in babbage for 'spread'.
Anyone.
> Ensure deployments spread over availability zones

- README.md
- config/config.go
- config/config_test.go
- main.go
- router/router.go
Removed remaining areas service handler, and config
Ensure only expected things removed, tests pass and README updated etc.
Anyone
> Remove areas service

- config/config.go
- go.sum
- main.go
- router/router.go
- Add route handler for previous releases `/previousreleases`
- Add config for toggling previous releases routes handler
Anyone
> Add route handler for previous releases

- assets/redirects/redirects.csv
> add atoz redirect

- README.md
- config/config.go
- config/config_test.go
- main.go
- router/router.go
- router/router_test.go
Route "*/relateddata" to go search-controller
Add config "RelatedDataRouteEnabled" for toggling related data routes handler
Check code is ok.
Run code and ensure routing is working when turned on.
Anyone
> route /relateddata to go search-controller

- .nancy-ignore
- README.md
add PREVIOUS_RELEASES_ROUTE_ENABLED documentation to README
Anyone
> add PREVIOUS_RELEASES_ROUTE_ENABLED documentation to README

- .github/CODEOWNERS
- assets/redirects/redirects.csv
- router/router.go
- router/router_test.go
These are the changes in this release:
- Add CODEOWNERS file - https://github.com/ONSdigital/dp-frontend-router/pull/490 - @lindenmckenzie
- Delete yorksurvey short url - https://github.com/ONSdigital/dp-frontend-router/pull/492 - @cookel2 
- Send bulletin extensions through cache proxy - https://github.com/ONSdigital/dp-frontend-router/pull/491 - @lindenmckenzie 
Check only expected commits present and tests pass
Anyone but me
> Release 1.94.0

- Dockerfile.local
Fix local docker git error for dubious ownership inline with the solution from our guidance:
https://github.com/ONSdigital/dp-operations/blob/main/troubleshooting/fixing-colima-related-errors.md.
!me
> Fix dubious ownership error on local docker

- assets/redirects/redirects.csv
Added redirect for UK bulletin that went out with wrong URL
Check it's ok
Not me.
> UK trade redirect

- Dockerfile.local
- Makefile
- README.md
- ci/audit.yml
- ci/build.yml
- ci/component.yml
- ci/lint.yml
- ci/unit.yml
- Switch audit tool from nancy to vulncheck
Check tests pass
!Me
> Switch audit tool from nancy to vulncheck
