ONSdigital/dp-frontend-router

- config/config.go
Update default babbage URL to be a local development environment not production
Run babbage locally, it should use that!
> update default babbage url

- handlers/homepage/handler.go
- main.go
- resolver/client.go
* Added logging when proxying babbage requests, and when homepage successfully renders
* Moved the request ID value to the log context
* Switch logging new request to logging original request (for context)
Start the router, check that successful requests for homepage and babbage are logged
> move request ID to context, add additional logging when successful

- main.go
- don't set cookie if it's not required
- reselect from a/b handlers if an invalid value is received
- configure AB handler percentage to 0, cookie should be ignored/not set, handler A used
- configure AB handler percentage to 100, cookie should be ignored/not set, handler B used
- configure AB handler percentage to 50, manually override cookie value to "C", router should reselect from A or B
> updates to ab handler

- assets/templates.go
- config/config.go
- handlers/splash/handler.go
- main.go
Add a disabled page to the router
* Run dp-frontend-router and check the site works
* Run it with `SPLASH_PAGE=dd/alpha` and check the splash page works, and that clicking the button allows you to access the site
* Run it with `DISABLED_PAGE=dd/alpha` and check you get the splash page, and that clicking the button does nothing (cookie should still be set, but is ignored)
> add disabled page

- main.go
Add X-Frame-Options header to responses except `/embed`
* Run the router
* Check HTTP responses for correct header
* Check that `/embed` responses don't have the header
> add X-Frame-Options header to all requests except /embed

- assets/debug.go
- handlers/splash/handler.go
Set cookie path
- clear `splash` cookie
- open a page on a non-root URL (e.g. `/economy/grossdomesticproductgdp`)
- check cookie path is `/`
> fix splash cookie path handling

- main.go
Prevent sameorigin header being returned for visualisations
- Run locally
- Check anything under /visualisations doesn't return X-Frame-Options header
> fix sameorigin bug

- assets/debug.go
- assets/templates.go
- handlers/serverError/handler.go
Return the correct status code when a downstream service returns an error (i.e. stop returning a 200 response for an internal server error page)
* Start dp-frontend-router
* Start dp-frontend-renderer
* `curl localhost:20000` should return a 500 error
* Stop dp-frontend-renderer
* `curl localhost:20000` should also return a 500 error
> return the correct status code for downstream errors

- dp-frontend-router.nomad
Updated nomad plans to removed operator:regexp and attribute:meta.has_disk.
Could not find dp-api-poc or dp-developer-poc.
https://trello.com/c/wKGU1LY5/3697-check-all-bau-services-nomad-plans
???
james
> removed operator:regexp

- assets/debug.go
- assets/templates.go
- middleware/serverError/handler.go
Prevent reflective Cross-Site Scripting attacks when a user gets a 500 page via a link to the website.
Escaped URL on the 500 page.
1. Pull this PR and run it locally, publish a dataset and go to a link like:
2. Open Firefox
3. Navigate to a page similar to: http://{domain}:{port}/datasets/cpih01/edditions/time-series/versions/19%25%7dcfv57'%3E%3Cscript%3Ealert(1)%3C/script%3E
3.a note anything that triggers a 500 page add:
` %25%7dcfv57'%3E%3Cscript%3Ealert(1)%3C/script%3E ` at the end 
4. You should not recieve an alert. Open up the dev console in browser inspect the refresh link, you should see something like this which includes: `%25%7Dcfv57%27%3E%3Cscript%3Ealert%281%29%3C%2Fscript%3E`
> Prevent reflective XSS attacks

- config/config.go
- config/config_test.go
Port for the dp-frontend-cookie-controller has changed
> Change port cookies controller can be found on

- main.go
- middleware/serverError/handler.go
Reintroduced the serverError package into the repo. I was a little too zelus in my removal of rendering in the router in a prior PR.
Note to compare what has actually changed by me and not just been readded compare [https://github.com/ONSdigital/dp-frontend-router/blob/master/middleware/serverError/handler.go](https://github.com/ONSdigital/dp-frontend-router/blob/master/middleware/serverError/handler.go)
A comparison can be seen here: https://www.diffchecker.com/I3vaDbeI
⚠️ Please only review what has actually changed in this PR and found on the above diff link. This PR is quite urgent as without it it is blocking quite a large chunk of work from being deployed. There is a lot in the file that shouldn't be the way it is, but this is out of scope for this 'fix'. ⚠️ 
Check that 404 status …
> serverError reintroduced

- go.mod
- go.sum
- middleware/serverError/handler.go
- Pass `req` object to error rendering functions so `cookies_preferences_set` and `cookies_policy` values are passed to the template. This allows us to determine whether or not the cookies banner should be rendered on the error pages (401/404)
- Check changes to the handler align with best practices
- Test locally that the cookies banner renders on an error page when cookies preferences have not been set and vice versa
Anyone but me
> update router to be cookie aware for error templates

- assets/redirects/redirects.csv
The Centre for Equalities and Inclusions section of the site now resides in a different path. This means that the previously used URL now 404s.
This PR adds a redirect from the old URL to the new URL.
- Check that the redirect aligns with requirements in the `WHAT` section of the [ticket](https://trello.com/c/OMxQnshZ/128-create-redirect-url-1-2)
- Test locally that the redirect works
Anyone but me
> add centre for equalities and inclusion redirect

- config/config.go
Added missing `"` at the end of the `HomepageControllerURL` config property.
> add missing quotation mark to homepage controller URL config entry

- assets/redirects/redirects.csv
This release cut adds the `/shapestudy` redirect
Ensure no other changes are present, other than the redirect
Anyone
> added redirect for shapestudy

- assets/redirects/redirects.csv
Added a redirect - `/householdstudies` => `/surveys/informationforhouseholdsandindividuals/householdandindividualsurveys`
Check locally that when you go to the short url, you are redirected to the long one (404 expected as we wouldn't have the page content locally)
Anyone but me
> Add /householdstudies redirect

- middleware/serverError/handler.go
Hotfix to be implemented so that 404 error page can display a warning for users that some datasets will have been moved owing to the Neptune migration.
This is specifically a small change to the 404 error msg that removes the copy to the sitemap, as per the prototype, because there is no reference to the sitemap on the homepage
- Check in conjunction with [this renderer PR](https://github.com/ONSdigital/dp-frontend-renderer/pull/532)
- Go to a page locally that'll give you a 404 - check that the copy and design matches [this prototype](https://deploy-preview-6--dp-prototypes.netlify.app/prototypes/status-banner/404-page) 
Anyone
> remove reference to sitemap in 404 error msg

- config/config.go
- main.go
**Describe what you have changed and why.**
- Remove the `NewHomepageEnabled` flag as the old homepage is no longer in `babbage` as it was removed. Therefore, there only exists the new homepage in which a feature flag is no longer needed. Also, this helps developers as well in which they do not need to set this feature flag to `true` whenever they try to retrieve the homepage when running services locally. 
**Describe the steps required to test the changes.**
- Check if the code changes make sense
- Check if the homepage still loads by running the web stack locally
- Check if `newHomepageEnabled` feature flag has been removed throughout
**Describe who worked on the changes, so that other people can review.**
Anyone - Justin made the changes.
> remove NewHomepageEnabled flag

- analytics/service.go
- analytics/service_test.go
- go.mod
- go.sum
- main.go
- middleware/allRoutes/handler.go
- middleware/redirects/redirects.go
- middleware/redirects/redirects_test.go
1. Use forked version of jwt-go lib that fixes the audit that nancy reports.
2. Add test code to show new lib fixes the problem, and if the test code is run against original library it shows it failing.
3. Code clean up of a few linter issues.
run:
make audit
make test
inspect test code
Anyone.
> Fix nancy audit failure by using forked jwt-go lib

- router/matcher.go
- router/matcher_test.go
- router/router_test.go
Send /data and /latest requests directly to babbage
Instead of letting /data and /latest requests into the allRoutesHandler, send them directly to Babbage. The allRoutesHandler makes a request to Zebedee to try and determine the page type. Requests to /data will not be recognised by Zebedee. Requests to /latest are only supported by the page types bulletin, article, and compendium. Only dataset page types are rerouted by the allRoutesHandler, it's more optimal to send /latest requests directly to Babbage.
Review changes / check I haven't broken anything
Anyone
> Send /data and /latest requests directly to Babbage

- config/config.go
- config/config_test.go
- main.go
Make the proxy timeout configurable so that we can increase the value if needed in production if we are experiences performance issues. When the requests timeout the user is returned a 502, so having the option of increasing the timeout as a support option is a useful tool.
Ensure that the changes make sense.
!me
> Make proxy timeout configurable

- README.md
- main.go
Fix a bug with the a/b testing of search; manipulating the dates for both old and new search may allow both to be rendered to the user.
- Manipulate the cookie by changing the expiry date for both old and new search to a time in the future and you should get new search results rendered only
Anyone
> Fix bug in a/b testing of new search

- router/router.go
- router/router_test.go
Remove  trailing slash from dp-census-atlas as it seems to be breaking proxying
Describe the steps required to test the changes.
Describe who worked on the changes, so that other people can review.
> remove trailing slash from dp-census-atlas routes

- config/config.go
- config/config_test.go
- main.go
- middleware/redirects/redirects.go
- middleware/redirects/redirects_test.go
**Describe what you have changed and why.**
- Redirect requests to `/searchdata` and `/searchpublication` to `/search`. 
- This should handle any query parameters on the end of uri and append this to `/search`
- The status code should return a `301`
**Describe the steps required to test the changes.**
- Check if the test passes
- Check if the code changes make sense
**Describe who worked on the changes, so that other people can review.**
- Anyone
> add search redirects

- assets/redirects/redirects.csv
Another redirect added, incorrect location of page on website moved to new location
Redirect from:
`<domain>/news/statementsandletters/measuringprogressgdpandbeyond`
to:
`<domain>/news/news/measuringprogressgdpandbeyond`
Anyone
> Redirect to new location of measuring progress gdp and beyond page

- router/router.go
- router/router_test.go
commit 76149aa0130ee619b546e6cf34456c69b133b1f9 (HEAD -> feat/new-url-for-census-atlas, origin/feat/new-url-for-census-atlas)
Author: Vivian Allen <vivian.allen@methods.co.uk>
Date:   Fri Sep 16 10:28:43 2022 +0100
census-atlas path /census-atlas -> /census/maps in router.go
- Move census-atlas (or census-maps as its now known) from its
old path at /census-atlas to its new one at /census/maps. This
is placed above the more general /census path in router.go to
avoid clashes.
These changes needed to better associate census-maps with census
content.
Read the code, check the tests pass
To test locally:
- run the front-end router locally with the census atlas routes enable with `CENSUS_ATLAS_ROUTES_ENABLED=true make debug`
- pull the census-atlas (https://github.com/ONSdigital/dp-census-atlas) …
> census-atlas path /census-atlas -> /census/maps in router.go

- router/router.go
- router/router_test.go
commit 3e64982ffebd39df6b8080d67ec0d813b87e3c57 (HEAD -> feature/add-x-frame-block-exception-for-census-maps, origin/feature/add-x-frame-block-exception-for-census-maps)
Author: Vivian Allen <vivian.allen@methods.co.uk>
Date:   Tue Oct 11 13:22:46 2022 +0100
add X-Frame-Options header exception for /census/maps
- Add /census/maps path to list of those excluded from having
X-Frame-Options: SAMEORIGIN header set in router.SecurityHandler
- Add /census/maps to list of tested paths in router_test.TestSecurityHandler
These changes needed to allow embedded of census-maps (aka dp-census-atlas)
in iFrames.
- Read the code
- Run the tests
- Try it locally:
* run this branch of dp-frontend-router locally with census atlas routes enabled: `CENSUS_ATLAS_ROUTES_ENABLED=True make debug`
* run …
> add X-Frame-Options header exception for /census/maps

- Dockerfile.local
- Makefile
- ci/build.yml
- ci/unit.yml
- go.mod
- reflex
- [Trello card](https://trello.com/c/S2KyzIGX/1024-create-census-hub-stack-using-docker)
- Modify `reflex` file to run `debug-run` instead of `debug`
- You may run the dp-compose stack using [the branch for this PR](https://github.com/ONSdigital/dp-compose/pull/123)
Anyone
> Modified reflex to run debug-run instead of debug

- README.md
- config/config.go
- main.go
- router/router.go
- router/router_test.go
Added routing for new dataset finder page, hosted within frontend search controller
With DATASET_FINDER_ENABLED off, router should fallback to babbage with /census/find-a-dataset. With it on, it should pass to dp-frontend-search-controller and 404 there instead. 
Developer.
> add routing for dataset finder

- README.md
- config/config.go
- config/config_test.go
- main.go
Added a new feature flag so that the requests to Babbage go to the proxy instead. 
Default value of _LEGACY_CACHE_PROXY_ENABLED_ is false
1. Run babbage `./run.sh`
2. Run zebedee `./run-reader.sh` (requires content to have been generated as described in the zebedee README.md prior to this)
3. Set _LEGACY_CACHE_PROXY_ENABLED_ to true by running this on the terminal
`export LEGACY_CACHE_PROXY_ENABLED=true`
4. Run dp-frontend-router `make debug`
5. This requires changes that are part of [this Draft PR](https://github.com/ONSdigital/dp-legacy-cache-proxy/pull/4) in order to check that the call is made to the dp-legacy-cache-proxy. Checkout the [branch](https://github.com/ONSdigital/dp-legacy-cache-proxy/tree/feature/proxy-pass-through) on the above PR and run in dp-legacy-cache-proxy `make …
> Legacy cache Proxy Feature Flag

- analytics/analyticstest/sqsclient.go
- go.mod
- go.sum
- main.go
- middleware/allRoutes/allroutestest/zebedeeclient.go
- middleware/datasetType/mocks/dataset.go
- middleware/datasetType/mocks/filter.go
- router/router.go
- router/router_test.go
- router/routertest/handler.go
When LegacyCacheProxyEnabled is true release calendar URLs are redirected to dp-legacy-cache-proxy 
1. Run dp-frontend-release-calendar with the required apps mentioned in its README
2. Run dp-frontend-router make debug and set LEGACY_CACHE_PROXY_ENABLED=true
3. This requires changes that are part of https://github.com/ONSdigital/dp-legacy-cache-proxy/pull/20 in order to check that the call is made to the dp-legacy-cache-proxy. Checkout the [branch](https://github.com/ONSdigital/dp-legacy-cache-proxy/tree/feature/release-calendar-redirect) on the above PR and run in dp-legacy-cache-proxy make debug
4. Make a request to a release calendar endpoint e.g. http://localhost:20000/releases/adoption
Anyone from ONS
> Redirect release calendar URLs to proxy

- assets/redirects/redirects.csv
There was a support request as follows:
Deadline: 2024-11-13
Question: Could the short URL https://www.ons.gov.uk/yorksurvey be removed please? It refers to a survey which has expired and the page it leads to will be deleted. Thanks!
Check that the correct URL has been deleted from the list.
Anyone but me!
> Delete yorksurvey short url

- router/router.go
- router/router_test.go
Routing bulletin/article/compenia extension pages (/previousreleases & /related[Dd]ata) through the legacy cache proxy
Check looks ok, tests pass, sufficient coverage, sensible approach. 
To run locally you can run:
- dp-frontend-router
- dp-frontend-search-controller
- babbage (requires es2.4.2)
- dp-legacy-cache-proxy
Use the feature flags to direct traffic different ways.
Not me.
> Send bulletin extensions through cache proxy

- README.md
- config/config.go
- config/config_test.go
Removed unused pattern library reference (used to be used for 404s but now deprecated)
Check haven't removed anything needed.
Not me.
> Remove unused sixteens library reference
